### ISSUE TITLE
EFCore missing method EntityTypeBuilder`1.HasIndex at runtime

### ISSUE THREAD

**Issue by Bert-Proesmans** [sergezhigunov/Hangfire.EntityFrameworkCore#6]
Hi

I'm using this library as an adapter between hangfire and my mysql database. Im encountering a runtime exception when the context is building/defining the models. (I'm using EFCore 3.1 as dependency withing my console projects)
This is probably exactly related to https://github.com/aspnet/AspNetCore/issues/8467.

I downloaded the project and updated the package references to EFCore 3.1. Using that project as dependency makes the runtime exception not occur anymore. 
I would have done a PR, but i assume updating the EFCore dependency of Hangfire.EntityFrameworkCore from 2.0 to 3.1 could be a backwards incompatible change for all users who are currently depending on the EFCore 2.X releases. Can this be tested? Maybe integrate two test projects where one depends on EFCore 2.X and the other depends on EFCore 3.X directly.

Currently i'm fine using my local copy of this library. I just wanted to let you know of this issue.

Bert

EDIT; Clarification of example projects

**Comment by sergezhigunov** [comment]
Hi 

@Bert-Proesmans Thank you for the information.
 I'll try to resolve this problem without any breaking changes with support from all the EFCore versions starting from 2.0 until next Monday.

Serge

**Comment by sergezhigunov** [comment]
Fixed. Now you can use the package with EFCore 2.* and 3.*.

**Comment by OpenSpacesAndPlaces** [comment]
Running into this error related to:
https://github.com/dotnet/aspnetcore/issues/17932

Using:
Microsoft.AspNetCore.Identity.EntityFrameworkCore - 2.2.0
Microsoft.EntityFrameworkCore - 3.1.0

The initial failure point is when:
`base.OnModelCreating`

Is trying to run for:
`IdentityDbContext`

**Comment by omer-tamir** [comment]
has anyone fount a fix for that? I am still getting this error message using EF core 3.2.1 
MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Metadata.Builders.IndexBuilder

Down the line I know there is one package that still uses EF 2.2.6 but I can't update it's version

**Comment by Bert-Proesmans** [comment]
@omermina There isn't 'a' fix because MS says using combinations of different major versions is at your own risk. They could have prevented developers from using dependencies accross major versions, but they didn't specify minimum and maximum versions on their transitive dependencies.

In this case we're talking about method signature changes involving generics. The best way to solve this would be to multi-target Hangfire.EntityFrameworkCore. Each target gets a unique reference to EFCode 2.X or 3.X.
This used to align perfect on the border between netstandard2.0 and netstandard2.1, but EFCore 3.X was backported to netstandard2.0. This workaround won't solve all version situations.

Managing Net dependencies is a lot of hassle, save yourself the trouble and consolidate ALL dependencies to a single major version. 
In other cases use only the minimum amount of dependencies to reach your goal, because there are more ecosystem issues like this with MS at the center.
